name: bad-chart_name
version: 1.0.0
appVersion: 1.0.0
description: Blah blah
icon: https://foldingathome.org/wp-content/uploads/2016/10/cropped-foldingathome-logo.png
keywords:
- folding
home: https://foldingathome.org/
