---
apiVersion: v1
kind: Service
metadata:
  name: bad_service_name
  namespace: default
spec:
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 6443
  sessionAffinity: None
  type: ClusterIP
> 
